# Netlify Configuration for Ethos Analytics

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# API route headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function configuration
[functions]
  node_bundler = "esbuild"
  included_files = ["lib/**", "components/**"]

# Environment variables (set these in Netlify dashboard)
# DATABASE_URL - PostgreSQL connection string (use Neon or Supabase)
# REDIS_URL - Redis connection string (use Upstash)
# OPENAI_API_KEY - Optional, for AI summaries
# SENTRY_DSN - Optional, for error tracking

